### ISSUE TITLE
(E.2) Components

### ISSUE THREAD

**Issue by mosser** [ace-lectures/atco-eats#15]
List of elements of the environment that may affect or be affected by the system and project. It includes other systems to which the system must be interfaced. These components may include existing systems, particularly software systems, with which the system will interact — by using their APIs (program interfaces), or by providing APIs to them, or both. These are interfaces provided to the system from the outside world. They are distinct from both: interfaces provided by the system to the outside world (<<s3>>); and technology elements that the system's development will require (<<p5>>).

**Comment by t-chiang** [comment]
I think there is one more external component and that is the inventory tracking system that already exists in the restaurant. There is very likely an already existing system for tracking sales and inventory that the system will need to integrate with.

Suggestion:
Sale and Inventory: The component implemented by the Firebird restaurant that already exists before the introduction of this app. As the app provides a new method of purchase for customers, it will need to integrate with existing systems at the Firebird in order to allow for inventory tracking and sales tracking to meet the goals of the restaurant manager stakeholder.

**Comment by mosser** [comment]
Good suggestion. We'll keep it for a second phase, and for now put an assumption that ATCO will not be integrated with the system. If the firebird agrees with that, it'll save us months of efforts (and this should not be usefull to demonstrate an MVP).
